# the config file of snakemake
workdir: "./"
Conda_yaml_dir: "envs/"
log_dir: "log/"
fna_dir: "fna_files/"
fmt_fna_dir: "fmt_fna/"
script_dir : 'scripts/'
db_path : "Database/"
db_prefix : "1Mar2023"
run_vConTACT: False